version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: sharewear-clothing-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=shu5Eyah5Phoikee6quolooqu7Ie
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - meilisearch_data:/meili_data

volumes:
  meilisearch_data:
    driver: local
